# Generated by Django 3.0.5 on 2020-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='output',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
