# Generated by Django 3.0.5 on 2020-05-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='output',
            new_name='feedback',
        ),
    ]
