# Generated by Django 3.0.5 on 2020-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20200510_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
